### ISSUE TITLE
Videos aren't saving to output directory

### ISSUE THREAD

**Issue by SkyrimFan64** [simontime/Brovicon#1]
Hi. Whenever I convert a video, It says the conversion finished but the video doesn't appear in the output directory.

**Comment by simontime** [comment]
What GPU does your computer have? Also do you have a pre-existing installation of AviSynth?

**Comment by SkyrimFan64** [comment]
My GPU is an NVIDA Geforce GTX 1650. Avisynth? I don't have that as I didn't see that being mentioned on the github page.

**Comment by simontime** [comment]
I'll have to add debug logging to figure this out - another user had the same issue until they uninstalled AviSynth, but since you don't have it installed I'm not sure what the issue is

**Comment by Wabbajackw** [comment]
Same issue here, Nvidia rtx 2070 super GPU and new windows installation (no AviSynth). Output file is not created

**Comment by simontime** [comment]
Installing (AviSynth+)[https://github.com/AviSynth/AviSynthPlus/releases/download/v3.7.2/AviSynthPlus_3.7.2_20220317.exe] should solve this issue.

**Comment by Wabbajackw** [comment]
Even if I install AviSynth+ same result. No output file.

**Comment by fenarinarsa** [comment]
> Even if I install AviSynth+ same result. No output file.

Try the following:
Download and run VirtualDub2 http://virtualdub2.com/
Try to convert your file in Brovicon
Drag & drop the file script.avs (that you can find in the avs folder of Brovicon) to VirtualDub2’s window
If you get an error message, upload a screenshot here.

**Comment by Wabbajackw** [comment]
![Capture d'écran 2023-06-22 225949](https://github.com/simontime/Brovicon/assets/98154552/d87a83e8-71eb-487d-9063-c10aae5fa0c9)

**Comment by fenarinarsa** [comment]
I guessed that you checked you had hqdn3d.dll in the avs folder?

Did you install the x64 version of AviSynth+?
https://avs-plus.net/

**Comment by Wabbajackw** [comment]
Yes, AviSynth+ is x64, after install Mkvtoolnix i can output an MKV file but it's cropped and process stopped before ending
I need to install all used codecs on your app and after make a deep complete test to see what's not working

**Comment by Wabbajackw** [comment]
I tried all codec the only one working for now is MKV, my dll is here all programs are x64 and i tried without denoising still same issue... My config is core i9 10850k RTX 2070 super. Maybe an issue with Nvidia drivers?
Btw the output fill is very heavy with poor quality :p
